import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { llmHealthTracker } from "../audit/llm-health.js";
import type { AuditEntry } from "../audit/logger.js";
import {
  callLlmApi,
  collectEmbeddedText,
  DEFAULT_EVAL_MODELS,
  PROVIDER_ENDPOINTS,
} from "../risk/llm-evaluator.js";
import type { EmbeddedAgentRuntime, ModelAuth } from "../types.js";
import { describeAction } from "./categories.js";

/**
 * Verbatim copy used when llmEnabled=false. Locked by tests so future copy
 * drifts are caught — see spec §8 L716-720.
 */
export const SUMMARY_LLM_DISABLED_MESSAGE =
  "Enable LLM evaluation in plugins.entries.clawlens.config.risk.llmEnabled to generate summaries.";

/** Build index of eval entries keyed by the toolCallId they reference. */
function buildEvalIndex(entries: AuditEntry[]): Map<string, AuditEntry> {
  const index = new Map<string, AuditEntry>();
  for (const e of entries) {
    if (e.refToolCallId && e.llmEvaluation) {
      index.set(e.refToolCallId, e);
    }
  }
  return index;
}

/** Get the effective risk score, preferring LLM-adjusted over Tier 1. */
function getEffectiveScore(
  entry: AuditEntry,
  evalIdx: Map<string, AuditEntry>,
): number | undefined {
  if (entry.toolCallId) {
    const evalEntry = evalIdx.get(entry.toolCallId);
    if (evalEntry?.llmEvaluation) return evalEntry.llmEvaluation.adjustedScore;
  }
  if (entry.llmEvaluation) return entry.llmEvaluation.adjustedScore;
  return entry.riskScore;
}

export interface SessionSummary {
  sessionKey: string;
  summary: string;
  generatedAt: string;
  /** True when generated by LLM, false for template fallback. */
  isLlmGenerated: boolean;
}

export type SummaryFailureReason = "not_found";

export type SessionSummaryResult =
  | { ok: true; summary: SessionSummary }
  | { ok: false; reason: SummaryFailureReason; message: string };

interface CacheEntry {
  summary: SessionSummary;
  expiresAt: number | null; // null = permanent (ended session)
}

const summaryCache = new Map<string, CacheEntry>();

const ACTIVE_SESSION_TTL_MS = 60_000; // 60s for active sessions

/**
 * Check if a session appears to still be active (last entry within 5 min).
 */
function isSessionActive(entries: AuditEntry[]): boolean {
  if (entries.length === 0) return false;
  let latest = entries[0].timestamp;
  for (const e of entries) {
    if (e.timestamp > latest) latest = e.timestamp;
  }
  return Date.now() - new Date(latest).getTime() < 5 * 60 * 1000;
}

/**
 * Generate a template summary for sessions with few entries.
 */
function templateSummary(
  sessionKey: string,
  entries: AuditEntry[],
  evalIdx: Map<string, AuditEntry>,
): SessionSummary {
  const decisions = entries.filter((e) => e.decision !== undefined);
  const count = decisions.length;

  let riskSum = 0;
  let riskCount = 0;
  for (const e of entries) {
    const score = getEffectiveScore(e, evalIdx);
    if (score !== undefined) {
      riskSum += score;
      riskCount++;
    }
  }
  const avgRisk = riskCount > 0 ? Math.round(riskSum / riskCount) : 0;

  return {
    sessionKey,
    summary: `Ran ${count} action${count !== 1 ? "s" : ""}. Avg risk: ${avgRisk}.`,
    generatedAt: new Date().toISOString(),
    isLlmGenerated: false,
  };
}

/**
 * Synthesize a "LLM disabled" summary that nudges the user toward the
 * opt-in config key. Spec §8 L716-720.
 */
function llmDisabledSummary(sessionKey: string): SessionSummary {
  return {
    sessionKey,
    summary: SUMMARY_LLM_DISABLED_MESSAGE,
    generatedAt: new Date().toISOString(),
    isLlmGenerated: false,
  };
}

/**
 * Build the LLM prompt for session summarization.
 * Note: action descriptions are derived from audit entries which already
 * carry sanitized params (the hook redacts before persistence). LLM payload
 * therefore never sees raw credential values.
 */
function buildSummaryPrompt(
  sessionKey: string,
  entries: AuditEntry[],
  evalIdx: Map<string, AuditEntry>,
): string {
  const decisions = entries
    .filter((e) => e.decision !== undefined)
    .sort((a, b) => a.timestamp.localeCompare(b.timestamp));

  const startTime = decisions[0]?.timestamp ?? "unknown";
  const endTime = decisions[decisions.length - 1]?.timestamp ?? "unknown";
  const startMs = new Date(startTime).getTime();
  const endMs = new Date(endTime).getTime();
  const durationMs = endMs - startMs;
  const durationStr =
    durationMs > 60000 ? `${Math.round(durationMs / 60000)}m` : `${Math.round(durationMs / 1000)}s`;

  let riskSum = 0;
  let riskCount = 0;
  let peakRisk = 0;
  for (const e of entries) {
    const score = getEffectiveScore(e, evalIdx);
    if (score !== undefined) {
      riskSum += score;
      riskCount++;
      if (score > peakRisk) peakRisk = score;
    }
  }
  const avgRisk = riskCount > 0 ? Math.round(riskSum / riskCount) : 0;

  const toolLines = decisions
    .slice(0, 30)
    .map((e) => {
      const desc = describeAction(e);
      const score = getEffectiveScore(e, evalIdx);
      const risk = score !== undefined && score >= 30 ? ` (risk ${score})` : "";
      return `- ${e.toolName}: ${desc}${risk}`;
    })
    .join("\n");

  const riskyActions = decisions
    .filter((e) => {
      const score = getEffectiveScore(e, evalIdx);
      return score !== undefined && score >= 50;
    })
    .slice(0, 5)
    .map((e) => {
      const desc = describeAction(e);
      const score = getEffectiveScore(e, evalIdx)!;
      return `- ${desc} (risk ${score})`;
    })
    .join("\n");

  const riskySection = riskyActions ? `\n\nElevated risk actions:\n${riskyActions}` : "";

  return `Describe this agent's activity pattern in one present-tense sentence (≤140 characters).

Session: ${sessionKey}
Duration: ${durationStr}
Actions: ${decisions.length}
Avg risk: ${avgRisk}, Peak: ${peakRisk}

Tool calls:
${toolLines}${riskySection}`;
}

/**
 * Content-shaped summary cap. See full doc on the exported function.
 */
export function capSummaryLength(raw: string, max = 400): string {
  for (let i = raw.length - 1; i >= 0; i--) {
    const ch = raw[i];
    if (ch === "." || ch === "!" || ch === "?") {
      if (i + 1 >= 40) return raw.slice(0, i + 1);
      break;
    }
  }
  if (raw.length <= max) return raw;
  const cut = raw.slice(0, max);
  const lastSpace = cut.lastIndexOf(" ");
  const boundary = lastSpace > max - 30 ? lastSpace : max;
  return `${cut.slice(0, boundary).trimEnd()}…`;
}

export interface SessionSummaryConfig {
  /**
   * Opt-in gate. When false (default), the path returns the LLM-disabled
   * message without contacting modelAuth or any provider endpoint.
   */
  llmEnabled: boolean;
  /**
   * Optional explicit model override. Leave empty/undefined to let the
   * summarizer derive the model from `DEFAULT_EVAL_MODELS[provider]`. Routes
   * should NOT hardcode this — that breaks non-Anthropic OpenClaw setups
   * (e.g. provider=openai would receive a Claude model name).
   */
  llmModel?: string;
  modelAuth?: ModelAuth;
  provider?: string;
  agent?: EmbeddedAgentRuntime;
  openClawConfig?: Record<string, unknown>;
}

/**
 * Get or generate a session summary.
 *
 * Returns `{ ok: true, summary }` for any session with entries — either the
 * LLM-generated summary, the template fallback, or the LLM-disabled message.
 * Returns `{ ok: false, reason: "not_found", ... }` when the session key has
 * no entries. Never throws; the HTTP layer branches on `result.ok`.
 */
export async function getSessionSummary(
  sessionKey: string,
  entries: AuditEntry[],
  config: SessionSummaryConfig,
): Promise<SessionSummaryResult> {
  let sessionEntries = entries.filter((e) => e.sessionKey === sessionKey);

  if (sessionEntries.length === 0) {
    const hashIdx = sessionKey.lastIndexOf("#");
    if (hashIdx !== -1) {
      const baseKey = sessionKey.slice(0, hashIdx);
      const runNum = parseInt(sessionKey.slice(hashIdx + 1), 10);
      const baseEntries = entries
        .filter((e) => e.sessionKey === baseKey)
        .sort((a, b) => a.timestamp.localeCompare(b.timestamp));
      const GAP_MS = 30 * 60 * 1000;
      const runs: AuditEntry[][] = [];
      let current: AuditEntry[] = [];
      for (const e of baseEntries) {
        if (current.length > 0) {
          const gap =
            new Date(e.timestamp).getTime() -
            new Date(current[current.length - 1].timestamp).getTime();
          if (gap > GAP_MS) {
            runs.push(current);
            current = [];
          }
        }
        current.push(e);
      }
      if (current.length > 0) runs.push(current);
      sessionEntries = runs[runNum - 1] ?? [];
    }
  }

  if (sessionEntries.length === 0) {
    return {
      ok: false,
      reason: "not_found",
      message: `No entries for sessionKey ${sessionKey}`,
    };
  }

  const cached = summaryCache.get(sessionKey);
  if (cached) {
    if (cached.expiresAt === null || Date.now() < cached.expiresAt) {
      return { ok: true, summary: cached.summary };
    }
    summaryCache.delete(sessionKey);
  }

  // Hard gate: opt-in LLM evaluation only. Never contact modelAuth/provider
  // when llmEnabled=false — spec §1 L182-191, §8 L716-720.
  if (!config.llmEnabled) {
    const summary = llmDisabledSummary(sessionKey);
    const active = isSessionActive(sessionEntries);
    summaryCache.set(sessionKey, {
      summary,
      expiresAt: active ? Date.now() + ACTIVE_SESSION_TTL_MS : null,
    });
    return { ok: true, summary };
  }

  const evalIdx = buildEvalIndex(entries);
  const decisions = sessionEntries.filter((e) => e.decision !== undefined);
  const active = isSessionActive(sessionEntries);

  let summary: SessionSummary;

  if (decisions.length < 3) {
    summary = templateSummary(sessionKey, sessionEntries, evalIdx);
  } else {
    const llmSummary = await generateLlmSummary(sessionKey, sessionEntries, config, evalIdx);
    summary = llmSummary ?? templateSummary(sessionKey, sessionEntries, evalIdx);
  }

  summaryCache.set(sessionKey, {
    summary,
    expiresAt: active ? Date.now() + ACTIVE_SESSION_TTL_MS : null,
  });

  return { ok: true, summary };
}

async function generateLlmSummary(
  sessionKey: string,
  entries: AuditEntry[],
  config: SessionSummaryConfig,
  evalIdx: Map<string, AuditEntry>,
): Promise<SessionSummary | null> {
  const prompt = buildSummaryPrompt(sessionKey, entries, evalIdx);
  const provider = config.provider || "anthropic";
  const model = config.llmModel || DEFAULT_EVAL_MODELS[provider];

  const needsDirectApi = model && PROVIDER_ENDPOINTS[provider];

  const systemPrompt = [
    "Describe what this agent has been up to in ONE plain-text sentence.",
    "Present tense. Pattern-focused, not event-by-event.",
    "Aim for ≤200 characters in one sentence — a complete thought matters more than the count. No markdown, no bullets, no follow-up.",
    "If any actions had elevated risk, briefly note them in the same sentence.",
    "Do not mention policy decisions, approvals, or blocking.",
    "Output the sentence directly. Nothing else.",
  ].join(" ");

  // Path 1: Embedded agent (handles auth internally)
  if (config.agent?.runEmbeddedPiAgent) {
    try {
      const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "clawlens-summary-"));
      const sessionFile = path.join(tmpDir, "session.json");
      try {
        const result = await config.agent.runEmbeddedPiAgent({
          sessionId: `clawlens:summary:${Date.now()}`,
          sessionFile,
          workspaceDir: process.cwd(),
          config: config.openClawConfig,
          prompt,
          extraSystemPrompt: systemPrompt,
          timeoutMs: 15_000,
          runId: `clawlens-summary-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
          provider: provider || undefined,
          model: model || undefined,
          disableTools: true,
          streamParams: { maxTokens: 100 },
        });
        const text = collectEmbeddedText(result.payloads);
        if (text) {
          llmHealthTracker.recordAttempt(true);
          return {
            sessionKey,
            summary: capSummaryLength(stripMarkdown(text)),
            generatedAt: new Date().toISOString(),
            isLlmGenerated: true,
          };
        }
        llmHealthTracker.recordAttempt(false, "embedded-agent: no text");
      } finally {
        await fs.rm(tmpDir, { recursive: true, force: true }).catch(() => {});
      }
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      llmHealthTracker.recordAttempt(false, errMsg);
      // Fall through to modelAuth path
    }
  }

  if (!needsDirectApi) return null;

  // modelAuth-resolved key only. v1.0.1 removed the explicit env-var
  // fallback that powered the earlier Path 3 here. Spec §1 L165-179.
  let apiKey: string | undefined;
  if (config.modelAuth && config.provider) {
    try {
      const auth = await config.modelAuth.resolveApiKeyForProvider({
        provider: config.provider,
        cfg: config.openClawConfig,
      });
      apiKey = auth?.apiKey;
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      llmHealthTracker.recordAttempt(false, errMsg);
      return null;
    }
  }

  if (!apiKey) {
    llmHealthTracker.recordAttempt(false, "modelAuth: no api key");
    return null;
  }

  const text = await callLlmApi(provider, apiKey, model!, systemPrompt, prompt, undefined, 100);
  if (!text) return null;

  return {
    sessionKey,
    summary: capSummaryLength(stripMarkdown(text)),
    generatedAt: new Date().toISOString(),
    isLlmGenerated: true,
  };
}

/**
 * Strip markdown artifacts that LLMs may include despite instructions.
 */
function stripMarkdown(raw: string): string {
  return raw
    .replace(/^#+\s+.*/gm, "")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/^[-*]\s+/gm, "")
    .replace(/^---+$/gm, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\n{2,}/g, " ")
    .replace(/\n/g, " ")
    .replace(/\s{2,}/g, " ")
    .trim();
}

/** Exposed for testing — clears the summary cache. */
export function clearSummaryCache(): void {
  summaryCache.clear();
}

/** Exposed for testing — get cache size. */
export function getSummaryCacheSize(): number {
  return summaryCache.size;
}
