import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import type { AuditEntry } from "../audit/logger";
import {
  callLlmApi,
  collectEmbeddedText,
  DEFAULT_EVAL_MODELS,
  PROVIDER_ENDPOINTS,
} from "../risk/llm-evaluator";
import type { EmbeddedAgentRuntime, ModelAuth } from "../types";
import { describeAction } from "./categories";

/** Build index of eval entries keyed by the toolCallId they reference. */
function buildEvalIndex(entries: AuditEntry[]): Map<string, AuditEntry> {
  const index = new Map<string, AuditEntry>();
  for (const e of entries) {
    if (e.refToolCallId && e.llmEvaluation) {
      index.set(e.refToolCallId, e);
    }
  }
  return index;
}

/** Get the effective risk score, preferring LLM-adjusted over Tier 1. */
function getEffectiveScore(
  entry: AuditEntry,
  evalIdx: Map<string, AuditEntry>,
): number | undefined {
  if (entry.toolCallId) {
    const evalEntry = evalIdx.get(entry.toolCallId);
    if (evalEntry?.llmEvaluation) return evalEntry.llmEvaluation.adjustedScore;
  }
  if (entry.llmEvaluation) return entry.llmEvaluation.adjustedScore;
  return entry.riskScore;
}

export interface SessionSummary {
  sessionKey: string;
  summary: string;
  generatedAt: string;
  /** True when generated by LLM, false for template fallback. */
  isLlmGenerated: boolean;
}

interface CacheEntry {
  summary: SessionSummary;
  expiresAt: number | null; // null = permanent (ended session)
}

const summaryCache = new Map<string, CacheEntry>();

const ACTIVE_SESSION_TTL_MS = 60_000; // 60s for active sessions

/**
 * Check if a session appears to still be active (last entry within 5 min).
 */
function isSessionActive(entries: AuditEntry[]): boolean {
  if (entries.length === 0) return false;
  let latest = entries[0].timestamp;
  for (const e of entries) {
    if (e.timestamp > latest) latest = e.timestamp;
  }
  return Date.now() - new Date(latest).getTime() < 5 * 60 * 1000;
}

/**
 * Generate a template summary for sessions with few entries.
 */
function templateSummary(
  sessionKey: string,
  entries: AuditEntry[],
  evalIdx: Map<string, AuditEntry>,
): SessionSummary {
  const decisions = entries.filter((e) => e.decision !== undefined);
  const count = decisions.length;

  // Avg risk using LLM-adjusted scores
  let riskSum = 0;
  let riskCount = 0;
  for (const e of entries) {
    const score = getEffectiveScore(e, evalIdx);
    if (score !== undefined) {
      riskSum += score;
      riskCount++;
    }
  }
  const avgRisk = riskCount > 0 ? Math.round(riskSum / riskCount) : 0;

  return {
    sessionKey,
    summary: `Ran ${count} action${count !== 1 ? "s" : ""}. Avg risk: ${avgRisk}.`,
    generatedAt: new Date().toISOString(),
    isLlmGenerated: false,
  };
}

/**
 * Build the LLM prompt for session summarization.
 */
function buildSummaryPrompt(
  sessionKey: string,
  entries: AuditEntry[],
  evalIdx: Map<string, AuditEntry>,
): string {
  const decisions = entries
    .filter((e) => e.decision !== undefined)
    .sort((a, b) => a.timestamp.localeCompare(b.timestamp));

  const startTime = decisions[0]?.timestamp ?? "unknown";
  const endTime = decisions[decisions.length - 1]?.timestamp ?? "unknown";
  const startMs = new Date(startTime).getTime();
  const endMs = new Date(endTime).getTime();
  const durationMs = endMs - startMs;
  const durationStr =
    durationMs > 60000 ? `${Math.round(durationMs / 60000)}m` : `${Math.round(durationMs / 1000)}s`;

  let riskSum = 0;
  let riskCount = 0;
  let peakRisk = 0;
  for (const e of entries) {
    const score = getEffectiveScore(e, evalIdx);
    if (score !== undefined) {
      riskSum += score;
      riskCount++;
      if (score > peakRisk) peakRisk = score;
    }
  }
  const avgRisk = riskCount > 0 ? Math.round(riskSum / riskCount) : 0;

  const toolLines = decisions
    .slice(0, 30)
    .map((e) => {
      const desc = describeAction(e);
      const score = getEffectiveScore(e, evalIdx);
      const risk = score !== undefined && score >= 30 ? ` (risk ${score})` : "";
      return `- ${e.toolName}: ${desc}${risk}`;
    })
    .join("\n");

  // Highlight risky actions separately so the LLM notices them
  const riskyActions = decisions
    .filter((e) => {
      const score = getEffectiveScore(e, evalIdx);
      return score !== undefined && score >= 50;
    })
    .slice(0, 5)
    .map((e) => {
      const desc = describeAction(e);
      const score = getEffectiveScore(e, evalIdx)!;
      return `- ${desc} (risk ${score})`;
    })
    .join("\n");

  const riskySection = riskyActions ? `\n\nElevated risk actions:\n${riskyActions}` : "";

  return `Summarize in 1-2 plain-text sentences. What did the agent accomplish? If any elevated risk actions are listed, mention them briefly. No markdown. No mention of approvals, policy, or blocking.

Session: ${sessionKey}
Duration: ${durationStr}
Actions: ${decisions.length}
Avg risk: ${avgRisk}, Peak: ${peakRisk}

Tool calls:
${toolLines}${riskySection}`;
}

/**
 * Get or generate a session summary.
 * Returns null if the session has no entries.
 */
export async function getSessionSummary(
  sessionKey: string,
  entries: AuditEntry[],
  config: {
    llmModel: string;
    llmApiKeyEnv: string;
    modelAuth?: ModelAuth;
    provider?: string;
    agent?: EmbeddedAgentRuntime;
    openClawConfig?: Record<string, unknown>;
  },
): Promise<SessionSummary | null> {
  let sessionEntries = entries.filter((e) => e.sessionKey === sessionKey);

  // Handle split session keys (e.g., "agent:bot:cron:job#2")
  if (sessionEntries.length === 0) {
    const hashIdx = sessionKey.lastIndexOf("#");
    if (hashIdx !== -1) {
      const baseKey = sessionKey.slice(0, hashIdx);
      const runNum = parseInt(sessionKey.slice(hashIdx + 1), 10);
      const baseEntries = entries
        .filter((e) => e.sessionKey === baseKey)
        .sort((a, b) => a.timestamp.localeCompare(b.timestamp));
      // Split by 30-min gaps and pick the right run
      const GAP_MS = 30 * 60 * 1000;
      const runs: AuditEntry[][] = [];
      let current: AuditEntry[] = [];
      for (const e of baseEntries) {
        if (current.length > 0) {
          const gap =
            new Date(e.timestamp).getTime() -
            new Date(current[current.length - 1].timestamp).getTime();
          if (gap > GAP_MS) {
            runs.push(current);
            current = [];
          }
        }
        current.push(e);
      }
      if (current.length > 0) runs.push(current);
      sessionEntries = runs[runNum - 1] ?? [];
    }
  }

  if (sessionEntries.length === 0) return null;

  // Check cache
  const cached = summaryCache.get(sessionKey);
  if (cached) {
    if (cached.expiresAt === null || Date.now() < cached.expiresAt) {
      return cached.summary;
    }
    // Expired — remove and regenerate
    summaryCache.delete(sessionKey);
  }

  // Build eval index from ALL entries — eval entries may not share the session key
  const evalIdx = buildEvalIndex(entries);
  const decisions = sessionEntries.filter((e) => e.decision !== undefined);
  const active = isSessionActive(sessionEntries);

  let summary: SessionSummary;

  if (decisions.length < 3) {
    summary = templateSummary(sessionKey, sessionEntries, evalIdx);
  } else {
    // Try LLM generation
    const llmSummary = await generateLlmSummary(sessionKey, sessionEntries, config, evalIdx);
    summary = llmSummary ?? templateSummary(sessionKey, sessionEntries, evalIdx);
  }

  // Cache: permanent for ended sessions, TTL for active
  summaryCache.set(sessionKey, {
    summary,
    expiresAt: active ? Date.now() + ACTIVE_SESSION_TTL_MS : null,
  });

  return summary;
}

async function generateLlmSummary(
  sessionKey: string,
  entries: AuditEntry[],
  config: {
    llmModel: string;
    llmApiKeyEnv: string;
    modelAuth?: ModelAuth;
    provider?: string;
    agent?: EmbeddedAgentRuntime;
    openClawConfig?: Record<string, unknown>;
  },
  evalIdx: Map<string, AuditEntry>,
): Promise<SessionSummary | null> {
  const prompt = buildSummaryPrompt(sessionKey, entries, evalIdx);
  const provider = config.provider || "anthropic";
  const model = config.llmModel || DEFAULT_EVAL_MODELS[provider];

  // Need a known provider and a model to proceed (for direct API paths)
  const needsDirectApi = model && PROVIDER_ENDPOINTS[provider];

  const systemPrompt = [
    "Return ONLY 1-2 plain-text sentences summarizing this agent session.",
    "Focus on what the agent accomplished.",
    "If any actions had elevated risk, briefly note them.",
    "Rules: no markdown, no headers, no bullet points, no follow-up questions, no commentary.",
    "Do not mention policy decisions, approvals, or blocking.",
    "Output the sentences directly, nothing else.",
  ].join(" ");

  // Path 1: Embedded agent (handles auth internally)
  if (config.agent?.runEmbeddedPiAgent) {
    try {
      const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "clawlens-summary-"));
      const sessionFile = path.join(tmpDir, "session.json");
      try {
        const result = await config.agent.runEmbeddedPiAgent({
          sessionId: `clawlens:summary:${Date.now()}`,
          sessionFile,
          workspaceDir: process.cwd(),
          config: config.openClawConfig,
          prompt,
          extraSystemPrompt: systemPrompt,
          timeoutMs: 15_000,
          runId: `clawlens-summary-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
          provider: provider || undefined,
          model: model || undefined,
          disableTools: true,
          streamParams: { maxTokens: 80 },
        });
        const text = collectEmbeddedText(result.payloads);
        if (text) {
          return {
            sessionKey,
            summary: stripMarkdown(text),
            generatedAt: new Date().toISOString(),
            isLlmGenerated: true,
          };
        }
      } finally {
        await fs.rm(tmpDir, { recursive: true, force: true }).catch(() => {});
      }
    } catch {
      // Fall through to direct API paths
    }
  }

  if (!needsDirectApi) return null;

  // Resolve API key: modelAuth first, then env var
  let apiKey: string | undefined;

  // Path 2: modelAuth-resolved key (fixed: object param, reads .apiKey)
  if (config.modelAuth && config.provider) {
    try {
      const auth = await config.modelAuth.resolveApiKeyForProvider({
        provider: config.provider,
        cfg: config.openClawConfig,
      });
      apiKey = auth?.apiKey;
    } catch {
      // Fall through to env var
    }
  }

  // Path 3: explicit env var
  if (!apiKey) {
    apiKey = process.env[config.llmApiKeyEnv];
  }

  if (!apiKey) return null;

  const text = await callLlmApi(provider, apiKey, model!, systemPrompt, prompt);
  if (!text) return null;

  return {
    sessionKey,
    summary: stripMarkdown(text),
    generatedAt: new Date().toISOString(),
    isLlmGenerated: true,
  };
}

/**
 * Strip markdown artifacts that LLMs may include despite instructions.
 * Returns clean plain text suitable for inline display.
 */
function stripMarkdown(raw: string): string {
  return raw
    .replace(/^#+\s+.*/gm, "") // remove headers
    .replace(/\*\*([^*]+)\*\*/g, "$1") // bold → plain
    .replace(/\*([^*]+)\*/g, "$1") // italic → plain
    .replace(/^[-*]\s+/gm, "") // remove bullet points
    .replace(/^---+$/gm, "") // remove horizontal rules
    .replace(/`([^`]+)`/g, "$1") // inline code → plain
    .replace(/\n{2,}/g, " ") // collapse double newlines
    .replace(/\n/g, " ") // remaining newlines → spaces
    .replace(/\s{2,}/g, " ") // collapse whitespace
    .trim();
}

/** Exposed for testing — clears the summary cache. */
export function clearSummaryCache(): void {
  summaryCache.clear();
}

/** Exposed for testing — get cache size. */
export function getSummaryCacheSize(): number {
  return summaryCache.size;
}
